<?php

/**
 * @name Subscribing to a webhook
 * 
 * This file documents how subscribe to a web hook. 
 * 
 * For demonstration purposes we are using a url generated by ngrok.
 */
require_once __DIR__ . '/../creating-a-new-connection.php';

$public_endpoint_url = 'https://b1fd1b40.ngrok.io/platoclient/webhooks/webhook-endpoint.php';

try {
    // Subscribe to all notifications about bookings.
    \tabs\apiclient\WebHook::subscribe($public_endpoint_url, 'actor');
} catch (Exception $ex) {
    echo $ex->getMessage();
}


require_once __DIR__ . '/../finally.php';

echo '<a href="../webhooks/webhook-endpoint.php">Next example ></a>';